ARG PBSPRO_GITHUB_PATH="pbspro"
ARG PBSPRO_REPO=https://github.com/$PBSPRO_GITHUB_PATH/pbspro.git
FROM pbspro/pbspro_base_202002:debian9 as builder
ARG PBSPRO_REPO
RUN adduser pbsuser && \
    sudo -u pbsuser git clone --single-branch --branch docker_builds "$PBSPRO_REPO" /home/pbsuser/pbspro && \
    sudo -u pbsuser /home/pbsuser/pbspro/k8s/build_pbspro.sh
