FROM pbspro/pbspro_build_202002:debian9 as builder
RUN /home/pbsuser/pbspro/k8s/install_pbspro_node.sh
LABEL maintainer="eric.pershey@gmail.com"
LABEL description="PBS Professional Open Source Server"
# in minikube 1.7, this should be there.
COPY ./docker-init /sbin/docker-init
ENTRYPOINT ["/sbin/docker-init", "--"]
CMD ["bash", "/home/pbsuser/pbspro/k8s/entrypoint_node.sh"]
# ulimit -H -s unlimited && \
# ulimit -S -s 65536 && \
# ulimit -n 10000 && \
# ulimit -l unlimited && \
