# base image for building pbspro
FROM pbspro/pbspro_base:centos7
RUN yum install -y lsof
RUN ssh-keygen -A
RUN updatedb
RUN ssh-keygen -f /root/.ssh/id_rsa -t rsa -N ""
RUN cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
