FROM pbspro/pbspro_base_202001:centos7 as builder
RUN adduser pbsuser && \
    sudo -u pbsuser git clone --single-branch --branch docker_builds https://github.com/${pbspro_repo}/pbspro.git /home/pbsuser/pbspro && \
    sudo -u pbsuser /home/pbsuser/pbspro/k8s/build.sh && \
    /home/pbsuser/pbspro/k8s/install_pbspro.sh

LABEL maintainer="eric.pershey@gmail.com"
LABEL description="PBS Professional Open Source Node"
ENTRYPOINT ["bash", "/home/pbsuser/pbspro/k8s/entrypoint_node.sh"]