# base image for building pbspro
FROM pbspro/pbspro_base:centos7
RUN yum install -y lsof
RUN ssh-keygen -A
RUN updatedb
RUN ssh-keygen -f /root/.ssh/id_rsa -t rsa -N ""
RUN cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
# THIS DOES NOT WORK, /etc/hosts is managed by docker
RUN echo "127.0.0.11 mom1"\
"127.0.0.12 mom2"\
"127.0.0.13 mom3"\
"127.0.0.14 mom4"\
>> /etc/hosts