apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pbspro-node
  name: pbspro-cluster-node
spec:
  #replicas: 5
  selector:
    matchLabels:
      app: pbspro-cluster-node
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pbspro-cluster-node
    spec:
      hostNetwork: true
      containers:
      - image: pbspro/pbspro_node_202001:centos7
        command: ["/etc/init.d/pbs"]
        args: ["start"]
        imagePullPolicy: IfNotPresent
        name: pbspro-node
        securityContext:
          privileged: true
        env:
          - name: LANG
            value: "en_US.UTF-8"
          - name: LANGUAGE
            value: "en_US.UTF-8"
          - name: LC_ALL
            value: "en_US.UTF-8"
          - name: LC_CTYPE
            value: "en_US.UTF-8"
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        ports:
        # - name: pbs-server
        #   containerPort: 15001
        # - name: pbs-comm
        #   containerPort: 17001
        # - name: pbs-server-ssh
        #   containerPort: 22              
        # readinessProbe:
        #   tcpSocket:
        #     port: 15001
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 15001
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
      volumeMounts:
        - name: config-volume-node
          mountPath: /etc/pbs.conf
          subPath: pbs.conf
      volumes:
      - name: config-volume-node
        configMap:
          name: pbspro-cluster-statefulset-node-configmap       
      dnsPolicy: ClusterFirst
      