apiVersion: v1
data:
  pbs.conf: |+
    PBS_CORE_LIMIT=unlimited
    PBS_EXEC=/opt/pbs
    PBS_HOME=/var/spool/pbs
    PBS_SCP=/usr/bin/scp
    PBS_SERVER=pbspro-pod-server
    PBS_START_COMM="0"
    PBS_START_MOM="1"
    PBS_START_SCHED="0"
    PBS_START_SERVER="0"
kind: ConfigMap
metadata:
  name: pbspro-cluster-statefulset-node-configmap
  namespace: default
