#!/bin/bash -xe
/opt/pbs/bin/qmgr -c "create node pbspro-node-0.pbspro-node.default.svc.cluster.local"
/opt/pbs/bin/qmgr -c "create node pbspro-node-1.pbspro-node.default.svc.cluster.local"
/opt/pbs/bin/qmgr -c "create node pbspro-node-2.pbspro-node.default.svc.cluster.local"
/opt/pbs/bin/qmgr -c "create node pbspro-node-4.pbspro-node.default.svc.cluster.local"
/opt/pbs/bin/qmgr -c "create node pbspro-node-3.pbspro-node.default.svc.cluster.local"
/opt/pbs/bin/qmgr -c "create node pbspro-node-5.pbspro-node.default.svc.cluster.local"
/opt/pbs/bin/qmgr -c "create node pbspro-node-6.pbspro-node.default.svc.cluster.local"
/opt/pbs/bin/qmgr -c "create node pbspro-node-7.pbspro-node.default.svc.cluster.local"
sudo /opt/pbs/bin/qmgr -c "create queue default"
sudo /opt/pbs/bin/qmgr -c "set queue default queue_type = Execution"
sudo /opt/pbs/bin/qmgr -c "set queue default enabled = True"
sudo /opt/pbs/bin/qmgr -c "set queue default started = True"
sudo /opt/pbs/bin/qmgr -c "set server flatuid = True"