apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pbspro
  name: pbspro-pod-server
spec:
  # hostNetwork: true
  containers:
  - name: pbspro-server # this is the pod name
    image: pbspro/pbspro_server_202001:centos7
    #command: 
    #- /etc/init.d/pbs
    #- "start"
    securityContext:
      privileged: true
    env:
      - name: LANG
        value: "en_US.UTF-8"
      - name: LANGUAGE
        value: "en_US.UTF-8"
      - name: LC_ALL
        value: "en_US.UTF-8"
      - name: LC_CTYPE
        value: "en_US.UTF-8"
      - name: HOSTNAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
    ports:
    - name: pbs-comm
      containerPort: 17001
    - name: pbs-server
      containerPort: 15001
    - name: pbs-server-ssh
      containerPort: 22      
    volumeMounts:
    - name: config-volume-server
      mountPath: /etc/pbs.conf
      subPath: pbs.conf
  volumes:
  - name: config-volume-server
    configMap:
      name: pbspro-cluster-pod-server-configmap
  dnsPolicy: ClusterFirst