apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: pbspro-node
  name: pbspro-node
spec:
  serviceName: pbspro-node #must match selector in the service
  replicas: 8
  selector:
    matchLabels:
      app: pbspro-node
  template:
    metadata:
      labels:
        app: pbspro-node
    spec:
      #hostNetwork: true
      containers:
      - name: pbspro-node
        imagePullPolicy: IfNotPresent
        image: pbspro/pbspro_node_centos7
        securityContext:
          privileged: true
        env:
          - name: LANG
            value: "en_US.UTF-8"
          - name: LANGUAGE
            value: "en_US.UTF-8"
          - name: LC_ALL
            value: "en_US.UTF-8"
          - name: LC_CTYPE
            value: "en_US.UTF-8"
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        ports:
        - name: a
          containerPort: 15003
        - name: b
          containerPort: 15002
        - name: c
          containerPort: 22
        volumeMounts:
          - name: config-volume-node
            mountPath: /etc/pbs.conf
            subPath: pbs.conf
      volumes:
      - name: config-volume-node
        configMap:
          name: pbspro-cluster-statefulset-node-configmap       
      dnsPolicy: ClusterFirst
      