apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pbspro
    tier: backend  
  name: pbspro-pod-server
spec:
  # hostNetwork: true
  containers:
  - name: pbspro-server # this is the pod name
    image: pbspro/pbspro_server_202001:centos7
    securityContext:
      privileged: true
    env:
      - name: PBS_START_MOM
        value: "0"
      - name: PBS_START_SERVER
        value: "1"
      - name: PBS_START_SCHED
        value: "1"
      - name: PBS_START_COMM
        value: "1"
      - name: HOSTNAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: status.podIP
    ports:
    - name: pbs-comm
      containerPort: 17001
    - name: pbs-server
      containerPort: 15001
    - name: pbs-server-ssh
      containerPort: 22      
  dnsPolicy: ClusterFirst