apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pbspro-cluster-server
spec:
  serviceName: "server"
  replicas: 1
  selector:
    matchLabels:
      app: pbspro-cluster-server
  template:
    metadata:
      labels:
        app: pbspro-cluster-server
    spec:
      #hostNetwork: true
      containers:
      - name: pbspro-server
        imagePullPolicy: IfNotPresent
        image: pbspro/pbspro_server_202001:centos7
        securityContext:
          privileged: true
        env:
          - name: PBS_START_MOM
            value: "0"
          - name: PBS_START_SERVER
            value: "1"
          - name: PBS_START_SCHED
            value: "1"
          - name: PBS_START_COMM
            value: "1"
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        ports:
        - name: pbs-server
          containerPort: 15001
        - name: pbs-comm
          containerPort: 17001
        # readinessProbe:
        #   tcpSocket:
        #     port: 15001
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 15001
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
      dnsPolicy: ClusterFirst
      