apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: pbspro-node  
  name: pbspro-cluster-node
spec:
  serviceName: "node"
  replicas: 1
  selector:
    matchLabels:
      app: pbspro-cluster-node
  template:
    metadata:
      labels:
        app: pbspro-cluster-node
    spec:
      #hostNetwork: true
      containers:
      - name: pbspro-node
        imagePullPolicy: IfNotPresent
        image: pbspro/pbspro_node_202001:centos7
        securityContext:
          privileged: true
        env:
          - name: LANG
            value: "en_US.UTF-8"
          - name: LANGUAGE
            value: "en_US.UTF-8"
          - name: LC_ALL
            value: "en_US.UTF-8"
          - name: LC_CTYPE
            value: "en_US.UTF-8"
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        ports:
        - name: pbs-server
          containerPort: 15001
        - name: pbs-comm
          containerPort: 17001
        # readinessProbe:
        #   tcpSocket:
        #     port: 15001
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 15001
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        volumeMounts:
          - name: config-volume-node
            mountPath: /etc/pbs.conf
            subPath: pbs.conf
      volumes:
      - name: config-volume-node
        configMap:
          name: pbspro-cluster-statefulset-node-configmap       
      dnsPolicy: ClusterFirst
      